---

# Install Jenkins
- name: Install Jenkins
  sudo: yes
  apt: pkg=jenkins state=latest update-cache=yes
  register: jenkins_install

# Save Jenkins data on a different partition if /data exists

- name: Check if jenkins data directory should be moved
  shell: ( [ -d /data ] && [ ! -d /data/jenkins ] && echo true ) || echo false
  register: should_move_jenkins

- name: Temporarily stop Jenkins
  service: name=jenkins state=stopped
  when: should_move_jenkins.stdout == "true"

- name: Move data directory
  shell: mv /var/lib/jenkins /data/jenkins
  when: should_move_jenkins.stdout == "true"

- name: Symlink data directory
  shell: ln -s /data/jenkins /var/lib/jenkins
  when: should_move_jenkins.stdout == "true"

- name: Restart Jenkins
  service: name=jenkins state=restarted enabled=true
  when: should_move_jenkins.stdout == "true"


# Install Jenkins cli
- include: cli.yml

# Install/update Jenkins plugins
- include: plugins.yml
