---
mesos_version: "0.24.1-0.2.35"
mesos_master_docker_image: "mesosphere/mesos-master:{{mesos_version}}.ubuntu1404"
mesos_agent_docker_image: "mesosphere/mesos-slave:{{mesos_version}}.ubuntu1404"
mesos_master_name: mesos_cluster
mesos_agent_name: mesos_agent
mesos_log_dir: "/var/log/mesos"
mesos_containerizers: "docker,mesos"
mesos_docker_stop_timeout: "30secs"
mesos_cluster_name: "mesos_cluster"
