---
mesos_version: "0.23.0"
mesos_master_docker_image: "mesoscloud/mesos-master:{{mesos_version}}-ubuntu-14.04"
mesos_agent_docker_image: "mesoscloud/mesos-slave:{{mesos_version}}-ubuntu-14.04"
mesos_master_name: mesos_cluster
mesos_agent_name: mesos_agent
mesos_log_dir: "/var/log/mesos"
mesos_containerizers: "docker,mesos"
mesos_docker_stop_timeout: "30secs"
mesos_cluster_name: "mesos_cluster"
