---
marathon_install_mode: "source" # 'bin' or 'source'
marathon_run_mode: "server" # 'server' or 'bridge'

marathon_version: "5230e908f3534d9379886b153f11e9a1eaf8fe50"
marathon_file_name:  "marathon-{{marathon_version}}.tgz"
marathon_download_url: "http://downloads.mesosphere.io/marathon/v{{marathon_version}}/{{marathon_file_name}}"

marathon_bin_folder: "/opt/marathon/{{marathon_version}}"

marathon_log_file: "/var/log/marathon.log"
marathon_zk: "zk://localhost:2181/marathon"
marathon_runtime_params: ""
