---
docker_machine_version: "0.3.0"
docker_machine_url: "{{'https://github.com/docker/machine/releases/download/v' ~ docker_machine_version ~ '/docker-machine_darwin-amd64'}}"
docker_keyserver: "hkp://p80.pool.sks-keyservers.net:80"
docker_keyserver_id: "58118E89F3A912897C070ADBF76221572C52609D"
docker_version: "docker-engine=1.8.3-0~trusty"
