---
- name: Make sure mesos-dns is running and config is up-to-date
  sudo: yes
  docker:
    image: "{{mesosdns_docker_image}}"
    name: "{{mesosdns_name}}"
    env:
      ENVIRONMENT: "debug"
      PARENT_HOST: "{{ inventory_hostname }}"
      MESOSDNS_MASTERS_1: "{{ marathon_host_servers | first }}:5050"
      MESOSDNS_RESOLVERS_1: "{{ mesosdns_dns_resolver }}"
      MESOSDNS_DOMAIN: "{{ mesosdns_dns_domain }}"
    ports:
      - "8123:8123"
      - "53:53"
    expose:
      - 8123
      - 53
    privileged: False
    net: host
    restart_policy: always
    state: restarted
