---
- apt_key: keyserver=keyserver.ubuntu.com id=C7A7DA52 state=present

- apt_repository: repo='deb http://apt.datadoghq.com/ stable main' update_cache=yes state=present

- apt: name=datadog-agent state=present

- template: src=datadog.conf.j2 dest=/etc/dd-agent/datadog.conf
  notify: Restart datadog
