---
- name: Apt install required system packages.
  apt: pkg={{item}} state=installed
  with_items:
    - openjdk-7-jre-headless

- name: Download mesos
  get_url: url={{mesos_download_url}} dest={{mesos_dest_file}}

- name: Install Mesos Debian Package
  shell: dpkg -i {{mesos_dest_file}}

- name: Download mesos python bindings (egg file)
  get_url: url={{mesos_python_download_url}} dest={{mesos_python_dest_file}}

- name: Install Mesos python bindings
  shell: easy_install {{mesos_python_dest_file}}

- name: Mesos default config file
  template: src=mesos.j2 dest=/etc/default/mesos

- name: Set mesos zookeeper config
  shell: echo {{mesos_zk}} | dd of=/etc/mesos/zk
