---
- name: Download marathon tarball
  get_url: url={{marathon_download_url}} dest={{marathon_dest_file}}

- name: Make sure bin folder exists
  file: state=directory path={{marathon_bin_folder}}

- name: Unpack marathon tarball.
  command: tar zxf {{marathon_dest_file}} --strip-components=1 -C {{marathon_bin_folder}} chdir=/tmp creates={{marathon_bin_folder}}/bin

- name: Delete marathon upstart script
  file: path=/etc/init/marathon.conf state=absent

- name: Marathon upstart script
  template: src=marathon.conf.j2 dest=/etc/init/marathon.conf
  notify:
    - Restart marathon
