---
- name: Install deimos
  pip: name=deimos

- name: Delete slave script
  file: path=/etc/init/mesos-slave.conf state=absent

- name: Mesos slave script
  template: src=mesos-slave.conf.j2 dest=/etc/init/mesos-slave.conf
  notify:
    - Restart mesos-slave
