---
- name: install kernel updates
  apt: pkg={{kernel_package}} state=latest update_cache=yes
  register: kernelup

- name: install other updates
  apt: upgrade=dist

- name: reboot the system
  command: reboot
  when: kernelup.changed

- name: Wait for SSH to come up
  wait_for:
    host: "{{ ansible_fqdn }}"
    port: 22
    delay: 60
    timeout: 120
    state: started
  when: kernelup.changed
