- name: Delete marathon upstart script
  file: path=/etc/init/marathon.conf state=absent

- name: Marathon upstart script
  template: src=marathon.conf.j2 dest=/etc/init/marathon.conf
  notify:
    - Restart marathon
