---
- hosts: all
  sudo: yes

  roles:
    - common

# Mesos masters
- hosts: mesos-masters
  gather_facts: false
  sudo: yes

  vars:
    - mesos_quorum: "{{ ((groups['mesos-masters'] | length) / 2) | round(0, 'ceil') | int }}"

  roles:
    - { role: zookeeper, tags: [ 'zookeeper' ] }
    - { role: mesosphere, tags: [ 'mesos' ], mesos_mode: master }
    - { role: marathon, tags: [ 'marathon'] }

# Mesos slaves
- hosts: mesos-slaves
  gather_facts: false
  sudo: yes

  vars:
    - mesos_options_slave:
        containerizers: "docker,mesos"
        executor_registration_timeout: 5mins

  roles:
    - { role: mesosphere, tags: [ 'mesos' ], mesos_mode: slave }
    - { role: marathon, tags: [ 'marathon'], marathon_run_mode: bridge }

# HAproxy
- hosts: haproxy
  gather_facts: false
  sudo: yes

  roles:
    - { role: haproxy, tags: [ 'haproxy' ] }

# VPN
- hosts: vpn
  gather_facts: false
  sudo: yes

  roles:
    - { role: openvpn, tags: [ 'vpn' ] }
