---
- hosts: mesos-slaves
  sudo: yes
  gather_facts: false

  tasks:
  - name: Create /var/marathon
    file: src=/var/marathon/  state=directory
  - name: Copy dockercfg to slaves
    copy: src=~/.dockercfg dest=/var/marathon/.dockercfg force=yes

- hosts: 127.0.0.1
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "deploy_env"
      prompt: "What environment would you like to deploy? [prod/test]"
    - name: "deploy_version"
      prompt: "What application version?"

  vars:
  - deploy_dockercfg_path: /var/marathon/.dockercfg
  - deploy_marathon_host: "{{ hostvars[groups['mesos-masters'][0]]['ansible_ssh_host']|default(groups['mesos-masters'][0]) }}"

  pre_tasks:
  - name: Check environment
    fail: msg="Unexisting environment"
    when: deploy_env != "prod" and deploy_env != "test"

  roles:
  - deploy
