---
- hosts: mesos-masters
  gather_facts: false
  sudo: yes

  roles:
    - common
    - { role: zookeeper, tags: [ 'zookeeper' ] }
    - { role: mesosphere, tags: [ 'mesos' ] }
    - { role: marathon, tags: [ 'marathon'] }
